version: '3.8'

services:
  best-z-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: best-z-nitrogen-dashboard-lowmem
    ports:
      - "8501:8501"
    volumes:
      # Mount data directory as read-only for security
      - ./BEST-Z/data_raw:/app/BEST-Z/data_raw:ro
      # Mount outputs directory for generated files
      - ./BEST-Z/outputs:/app/BEST-Z/outputs
    environment:
      - PYTHONPATH=/app/BEST-Z
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=true
      # Memory optimization settings
      - STREAMLIT_SERVER_MAX_MESSAGE_SIZE=50
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 60s  # Less frequent checks to save resources
      timeout: 15s
      retries: 2
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'

networks:
  default:
    name: best-z-lowmem-network