version: '3.8'

services:
  best-z-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: best-z-nitrogen-dashboard-prod
    ports:
      - "80:8501"  # Map to port 80 for production
    volumes:
      # Mount data directory as read-only for security
      - ./BEST-Z/data_raw:/app/BEST-Z/data_raw:ro
      # Mount outputs directory for generated files
      - ./BEST-Z/outputs:/app/BEST-Z/outputs
    environment:
      - PYTHONPATH=/app/BEST-Z
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=true
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  default:
    name: best-z-prod-network